apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: vmexamples-userX
spec:
  selector:
    vm.kubevirt.io/name: database-userX
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
