---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-fedora01
  namespace: oadp-userX
  labels:
    velero.io/storage-location: default
spec:
  defaultVolumesToFsBackup: false
  orLabelSelectors:
  - matchLabels:
      app: fedora01
  - matchLabels:
      vm.kubevirt.io/name: fedora01
  csiSnapshotTimeout: 10m0s
  ttl: 720h0m0s
  itemOperationTimeout: 4h0m0s
  storageLocation: oadp-dpa-1
  hooks: {}
  includedNamespaces:
  - vmexamples-userX
  snapshotMoveData: false
