apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-fedora02
  labels:
    velero.io/storage-location: default
  namespace: openshift-adp
spec:
  hooks: {}
  orLabelSelectors:
  - matchLabels:
      app: fedora02
  - matchLabels:
      vm.kubevirt.io/name: fedora02
  includedNamespaces:
  - vmexamples
  storageLocation: oadp-dpa-1
  ttl: 720h0m0s
